os: "linux"
dist: "xenial"
language: node_js
node_js:
  - 10
  - 12
  - 14
before_install:
  # https://github.com/conventional-changelog/commitlint/issues/6
  - git remote set-branches origin master && git fetch
jobs:
  include:
    - stage: release
      node_js: lts/*
      deploy:
        on:
          branch: master
        provider: script
        script: npx semantic-release
